config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(pattern_name='weather:weather', permanent=False), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("weather/", include("weatherapp.weather.urls", namespace="weather")),
    path("users/", include("weatherapp.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

weatherapp/users/urls.py
from django.urls import path

from weatherapp.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

weatherapp/weather/urls.py
from django.urls import path

from weatherapp.weather.views import (
    LocationListView,
    LocationDeleteView,
    LocationSaveView
)

app_name = "weather"
urlpatterns = [
    path("", view=LocationListView.as_view(), name="weather"),
    path("save-location", LocationSaveView.as_view(), name="save-location"),
    path('delete-location/<int:pk>', LocationDeleteView.as_view(), name='delete-location'),

]

weatherapp/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for WeatherApp.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

weatherapp/weather/models.py
from django.db import models

class Location(models.Model):
    """Location model.

    A location represented by a title and a zipcode.
    """
    title = models.CharField("Title", max_length=150)
    zipcode = models.CharField("ZIP Code", max_length=5)

    def __str__(self):
        return self.title

weatherapp/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

weatherapp/weather/forms.py
from django import forms
from weatherapp.weather.models import Location

class LocationForm(forms.ModelForm):
    """Location form."""
    class Meta:
        model = Location
        fields = ['title','zipcode']

weatherapp/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

weatherapp/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):

    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

weatherapp/weather/api/views.py
from rest_framework.filters import SearchFilter
from rest_framework.viewsets import ModelViewSet
from weatherapp.weather.models import Location
from .serializers import LocationSerializer

class LocationViewSet(ModelViewSet):
    """
    A viewset for viewing and editing location instances.
    """
    serializer_class = LocationSerializer
    queryset = Location.objects.all()
    search_fields = ['zipcode']
    filter_backends = (SearchFilter,)

weatherapp/weather/views.py
from django.conf import settings
from django.urls import reverse_lazy
from django.views.generic import ListView, FormView
from django.views.generic.edit import DeleteView
from weatherapp.weather.forms import LocationForm
from weatherapp.weather.models import Location
import requests
# Create your views here.

class LocationListView(ListView):
    """Location list view.

    Handle retreiving the list of locations and fetching weather data from api.openweathermap.org
    """
    model =  Location
    context_object_name = "locations"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        zipcode = self.request.GET.get("zipcode")
        weather_request_url = f'{settings.WEATHER_API_PROVIDER_BASE_URL}weather?zip={zipcode},us&units=imperial&appid={settings.WEATHER_API_PROVIDER_APP_ID}'
        weather_data = requests.get(weather_request_url).json()
        if weather_data['cod'] == 200:
            context["data"] = weather_data
        return context
    
class LocationDeleteView(DeleteView):
    """Location delete view.

    Handles deleting a location
    """
    model = Location
    success_url = reverse_lazy('weather:weather')

class LocationSaveView(FormView):
    """Location save view.

    Handles saving a location when the zipcode doesnt already exists.
    """
    form_class = LocationForm
    success_url = reverse_lazy('weather:weather')
    def form_valid(self, form):
        location = form.save(commit=False)
        if not Location.objects.filter(zipcode=location.zipcode).exists():
            location.save()
        return super().form_valid(form)

weatherapp/templates/weather/location_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <form method="post">{% csrf_token %}
        <h2>Are you sure you want to delete "{{ object }}"?</h2>
        {{ form }}
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
</div>

{% endblock  %}

weatherapp/templates/weather/location_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">     <span class="navbar-toggler-icon"></span>     </button>         
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
             <li class="nav-item active">               </li>
             <li class="nav-item">                </li>
             <li class="nav-item">                </li>
          </ul>
          <form method="GET" class="form-inline my-2 my-lg-0" _lpchecked="1"><input class="form-control location-autocomplete mr-sm-2" autocomplete="off" name="zipcode" type="text" maxlength="5" placeholder="Zip Code" aria-label="Zip Code" style="width:250px">       <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>      </form>
       </div>
    </nav>
    <footer class="footer">
       <ul class="list-group" style="">
          {% for location in locations  %}
             <li class="list-group-item">
                <a href="{% url 'weather:weather' %}?zipcode={{location.zipcode}}">{{location.title}}</a>
                <a href="{% url 'weather:delete-location' location.pk %}" class="btn btn-default" style="display: inline; float: right;">X</a>
            </li>
          {% endfor %}
       </ul>
       {% comment %} <p contenteditable="true" spellcheckker="false"> {% endcomment %}
        {% if data %}
       <div class="card" style="margin-top: 30px;">
          <div class="card" style="margin-top: 0px;">
             <div class="card-body" style="margin-top: 0px;">
                <h4 class="card-title">
                   <b>{{data.name}}</b>
                </h4>
                <form method="POST" action="{% url 'weather:save-location' %}">                
                    <div class="row" style="">
                        <div class="col-sm-4">
                            <h1>
                            {{data.main.temp|floatformat:"0"}}°
                            {% for item in data.weather %}
                                <h6 style="">{{item.description}} <img src="http://openweathermap.org/img/w/{{item.icon}}.png" alt=""></h6>
                            {% endfor %}
                            </h1>
                        </div>
                        <div class="col-sm-4 col-5">
                            <h3></h3>
                        </div>
                        <div class="col-sm-4">
                            <h5 style="">Precipitation {% if data.rain %}{{data.rain.1h|floatformat:"0"}}{% else %}0{% endif %} mm</h5>
                            <h5 style="">Humidity {{data.main.humidity}}%</h5>
                            <h5 style="">Wind {{data.wind.speed|floatformat:"0"}} mph</h5>
                            <div class="row" style="">
                            <div class="col-sm-4"></div>
                            <div class="col-sm-4 col-5"></div>
                            <div class="col-sm-4"></div>
                            </div>
                        </div>
                    </div>
                    {% csrf_token %}
                    <input type="hidden" value="{{data.name}}" name="title">
                    <input type="hidden" value="{{request.GET.zipcode}}" name="zipcode">
                    <button type="submit" class="btn btn-primary">Add to favorites</button>    
                </form>
             </div>
          </div>
       </div>
       {% endif %}
       © Firstly NodeJS 2021</p>
    </footer>
 </div>
 <!-- /container -->
{% endblock  %}
{% block js %}
<script src="//code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="//stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>
<script>
    $(document).ready(function(){
        $('.location-autocomplete').autoComplete({
            resolver: 'custom',
            formatResult: function (item) {
                return {
                    value: item.zipcode,
                    text: item.zipcode,
                    html: [ 
                            item.zipcode, ' - ',
                            item.title 
                        ] 
                };
            },
            events: {
                search: function (qry, callback) {
                    // let's do a custom ajax call
                    $.ajax(
                        '/api/locations.json',
                        {
                            data: { 'search': qry}
                        }
                    ).done(function (res) {
                        callback(res)
                    });
                }
            }
        });
    });
    
</script>
{% endblock js %}